version: "3.8"

services:
  challenge-n13-mongodb:
    hostname: challenge-n13-mongodb
    restart: always
    container_name: challenge-n13-mongodb
    build:
      context: docker/challenge-n13-mongo
      dockerfile: Dockerfile
    env_file:
      - docker/env-files/mongo.env
    volumes:
      - mongodb_data:/data
    command: mongod --auth
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
    driver: local
